USE master
GO
IF DB_ID('QLPK') IS NOT NULL
	DROP DATABASE QLPK
GO
CREATE DATABASE QLPK
GO

USE QLPK
GO

CREATE TABLE BENHNHAN 
(
	IDBENHNHAN CHAR(8),
	TENBN NVARCHAR(20) NOT NULL,
	NAMSINH DATE NOT NULL,
	GIOITINH NVARCHAR(3) NOT NULL,
	SODIENTHOAI CHAR(10) NOT NULL,
	TUOI INT NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	MATKHAU VARCHAR(10),
	BACSIMD CHAR(8)

	CONSTRAINT PK_BN
	PRIMARY KEY(IDBENHNHAN)
	CONSTRAINT CK_BENHNHAN_PHAI
	CHECK (GIOITINH = N'NAM' OR GIOITINH = N'NỮ'),
	CONSTRAINT UC_BENHNHAN_SDT UNIQUE (SODIENTHOAI)
)

CREATE TABLE KEHOACHDIEUTRI 
(
	IDDIEUTRI CHAR(10),
	MOTA NVARCHAR(30) NOT NULL,
	TRANGTHAI NCHAR(10) NOT NULL,
	GHICHU NVARCHAR(30) NOT NULL,
	TONGGIA FLOAT NOT NULL,

	BENHNHAN CHAR(8) NOT NULL,
	BSPHUTRACH CHAR(8) NOT NULL,
)

--THIẾU
CREATE TABLE BUOIDIEUTRI
(
	IDBUOIDIEUTRI CHAR(10),
	MOTABDT NVARCHAR(30) NOT NULL,
	GHICHUBDT NVARCHAR(30) NOT NULL,
	NGAYDT DATE NOT NULL,

	TROKHAM CHAR(8),
	KHAMCHINH CHAR(8) NOT NULL,
	KEHOACHDT CHAR(10) NOT NULL,
)

CREATE TABLE HOADON
(
	IDHOADON CHAR(15),
	TONGTIEN FLOAT NOT NULL,
	TIENDATRA FLOAT NOT NULL,
	LOAITHANHTOAN NVARCHAR(12) NOT NULL,
	GHICHUHOADON NVARCHAR(50),
	NGAYGIAODICH DATE NOT NULL,
	
	IDBENHNHAN CHAR(8) NOT NULL,
	IDBUOIDIEUTRI CHAR(10) NOT NULL
)

CREATE TABLE DONTHUOC
(
	IDDONTHUOC CHAR(12),
	NGAYCAP DATE NOT NULL,

	IDBUOIDIEUTRI CHAR(10)
)

CREATE TABLE CHITIETDONTHUOC
(
	IDTHUOC CHAR(8),
	IDDONTHUOC CHAR(12) NOT NULL,
	SOLUONG INT NOT NULL
)

CREATE TABLE THUOC
(
	IDTHUOC CHAR(8),
	TENTHUOC NCHAR(30) NOT NULL,
	THANHPHAN NCHAR(30) NOT NULL,
	DONVITINH NCHAR(10) NOT NULL,
	GIATHUOC FLOAT NOT NULL,
)

CREATE TABLE CHITIETDIEUTRI
(
	IDBUOIDIEUTRI CHAR(10) NOT NULL,
	MADIEUTRI CHAR(5) NOT NULL,
)

CREATE TABLE RANGDIEUTRI
(
	IDBUOIDIEUTRI CHAR(10) NOT NULL,
	MADIEUTRI CHAR(5) NOT NULL,
	TENRANG NCHAR(10) NOT NULL,
	MATDIEUTRI CHAR(1) NOT NULL
)

CREATE TABLE LOAIDIEUTRI
(
	MADIEUTRI CHAR(5),
	TENDIEUTRI NVARCHAR(30),
	GIA FLOAT,

	MADANHMUC CHAR(2)
)

CREATE TABLE DANHMUCDIEUTRI
(
	MADANHMUC CHAR(2),
	TENDM NVARCHAR(30),
)

CREATE TABLE NHANVIEN
(
	IDNHANVIEN CHAR(8),
	TENNV NVARCHAR(255),
	NAMSINH DATE,
	GIOITINH NVARCHAR(3),
	SODIENTHOAI CHAR(10),
	MATKHAU VARCHAR(10),
	LOAINV CHAR(10),

	IDPHONGKHAM CHAR(3)
)


CREATE TABLE LICHLAMVIEC
(
	IDNHANVIEN CHAR(8),
	NGAY INT,
	THANG INT,
	NAM INT,
)

CREATE TABLE LICHHEN
(
	LICHHEN DATE,
	THOIGIAN TIME,
	TINHTRANG NVARCHAR(10),
	PHONG NCHAR(5),
	GHICHULICHHEN NVARCHAR(30),

	KHAMCHINH CHAR(8),
	TROKHAM CHAR(8),
	BENHNHAN CHAR(8)
)

CREATE TABLE PHONGKHAM
(
	IDPHONGKHAM CHAR(3),
	TENPK NVARCHAR(30),
	DIACHIPK NVARCHAR(30),
	LIENHE CHAR(10),
)

CREATE TABLE HOSOBENHNHAN
(
	IDHOSO CHAR(10),
	TTTONGQUAN NVARCHAR(30),
	TINHTRANGDIUNG NVARCHAR(10),
	THUOCCHONGCHIDINH NVARCHAR(30),
	TONGTIEN FLOAT,
	DATHANHTOAN FLOAT,

	IDBENHNHAN CHAR(8)
)
