CREATE OR ALTER PROC SP_XOA1CHITIETDONTHUOC
	@IDDONTHUOC CHAR(12),
	@IDTHUOC CHAR(8)
AS
SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
BEGIN TRY
		IF NOT EXISTS (SELECT * FROM DONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC)
		BEGIN
			PRINT @IDDONTHUOC + 'KHONG TON TAI'
			ROLLBACK TRAN
			RETURN 1		 
		END
		IF NOT EXISTS (SELECT * FROM THUOC WHERE IDTHUOC = @IDTHUOC)
		BEGIN
			PRINT @IDTHUOC + 'KHONG TON TAI'
			ROLLBACK TRAN
			RETURN 1
		END

		IF NOT EXISTS (SELECT * FROM CHITIETDONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC AND IDTHUOC = @IDTHUOC)
		BEGIN
			PRINT 'IDTHUOC KHONG TON TAI TRONG DON THUOC'
			ROLLBACK TRAN
			RETURN 1
		END
		---- TEST---------------


 		
		DECLARE @IDBUOIDIEUTRI CHAR(10)
		SELECT @IDBUOIDIEUTRI = IDBUOIDIEUTRI FROM DONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC

		IF NOT EXISTS (SELECT * FROM HOADON WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI AND NGAYGIAODICH  IS NULL)
		BEGIN
			PRINT 'DON THUOC DA THANH TOAN KHONG THE THEM'
			ROLLBACK TRAN
			RETURN 1
		END

		--SELECT * FROM HOADON WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI AND NGAYGIAODICH IS  NULL
		DECLARE @SOLUONG INT
		SELECT @SOLUONG= SOLUONG FROM CHITIETDONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC AND IDTHUOC = @IDTHUOC
		--WAITFOR DELAY '0:0:10'
		DECLARE @TONGTIEN FLOAT
		SELECT @TONGTIEN = TONGTIEN FROM BUOIDIEUTRI WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI

		DECLARE @TIEN FLOAT
		SET @TIEN = (SELECT GIATHUOC * @SOLUONG FROM THUOC WHERE IDTHUOC = @IDTHUOC)
		SET @TONGTIEN = @TONGTIEN - @TIEN

		WAITFOR DELAY '0:0:5'

		
		UPDATE BUOIDIEUTRI
		SET TONGTIEN = @TONGTIEN
		WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI

		

		UPDATE HOADON
		SET TONGTIEN = @TONGTIEN
		WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI 

	-----ĐỂ TEST
		--WAITFOR DELAY '0:0:20'		 

		DELETE FROM CHITIETDONTHUOC 
		WHERE IDDONTHUOC = @IDDONTHUOC AND IDTHUOC =@IDTHUOC

		--UPDATE CHITIETDONTHUOC
		--SET SOLUONG = 5
		--WHERE IDDONTHUOC = @IDDONTHUOC AND IDTHUOC = @IDTHUOC
	-------

	END TRY
	BEGIN CATCH		PRINT N'LỖI HỆ THỐNG'		SELECT ERROR_MESSAGE() AS ErrorMessage;		ROLLBACK TRAN		RETURN 1	END CATCHCOMMIT TRANRETURN 0
GO


--CREATE OR ALTER PROC SP_THEM1CHITIETDONTHUOC
--	@IDDONTHUOC CHAR(12),
--	@IDTHUOC CHAR(8),
--	@SOLUONG INT
	
--AS
--SET TRAN ISOLATION LEVEL REPEATABLE READ
--BEGIN TRAN

--	BEGIN TRY
--		IF NOT EXISTS (SELECT * FROM DONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC)
--		BEGIN
--			PRINT @IDDONTHUOC + 'KHONG TON TAI'
--			ROLLBACK TRAN
--			RETURN 1
--		END
--		IF NOT EXISTS (SELECT * FROM THUOC WHERE IDTHUOC = @IDTHUOC)
--		BEGIN
--			PRINT @IDTHUOC + 'KHONG TON TAI'
--			ROLLBACK TRAN
--			RETURN 1
--		END

--		--IF EXISTS (SELECT * FROM CHITIETDONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC AND IDTHUOC = @IDTHUOC)
--		--BEGIN
--		--	PRINT 'IDTHUOC  TON TAI TRONG DON THUOC'
--		--	ROLLBACK TRAN
--		--	RETURN 1
--		--END

--		DECLARE @IDBUOIDIEUTRI CHAR(10)
--		SET @IDBUOIDIEUTRI = (SELECT IDBUOIDIEUTRI FROM DONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC)


--		IF EXISTS (SELECT * FROM HOADON WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI AND NGAYGIAODICH IS NOT NULL)
--		BEGIN
--			PRINT 'DON THUOC DA THANH TOAN KHONG THE THEM'
--			ROLLBACK TRAN
--			RETURN 1
--		END
--		--SELECT @IDBUOIDIEUTRI
--		--SELECT * FROM HOADON WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI AND  NGAYGIAODICH IS NULL
--		--WAITFOR DELAY '0:0:3'
--		DECLARE @TIEN FLOAT
--		SET @TIEN = (SELECT GIATHUOC * @SOLUONG FROM THUOC WHERE IDTHUOC = @IDTHUOC)
--		WAITFOR DELAY '0:0:10'

		
--		UPDATE BUOIDIEUTRI
--		SET TONGTIEN = TONGTIEN + @TIEN
--		WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI
--		UPDATE HOADON
--		SET TONGTIEN = TONGTIEN + @TIEN
--		WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI AND  NGAYGIAODICH IS NULL

--	-----ĐỂ TEST		
--		INSERT CHITIETDONTHUOC(IDDONTHUOC, IDTHUOC, SOLUONG)
--		VALUES (@IDDONTHUOC, @IDTHUOC, @SOLUONG)
--	-------

--	END TRY
--	BEGIN CATCH--		PRINT N'LỖI HỆ THỐNG'--		SELECT ERROR_MESSAGE() AS ErrorMessage;--		ROLLBACK TRAN--		RETURN 1--	END CATCH--COMMIT TRAN--RETURN 0

CREATE OR ALTER PROC SP_THEMCHITIETDONTHUOC
	@IDDONTHUOC CHAR(12),
	@IDTHUOC CHAR(8),
	@SOLUONG INT
AS
SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS (SELECT * FROM DONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC)
		BEGIN
			PRINT @IDDONTHUOC + 'KHONG TON TAI'
			ROLLBACK TRAN
			RETURN 1
		END
		IF NOT EXISTS (SELECT * FROM THUOC WHERE IDTHUOC = @IDTHUOC)
		BEGIN
			PRINT @IDTHUOC + 'KHONG TON TAI'
			ROLLBACK TRAN
			RETURN 1
		END

		DECLARE @IDBUOIDIEUTRI CHAR(10)
		SET @IDBUOIDIEUTRI = (SELECT IDBUOIDIEUTRI FROM DONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC)

		IF NOT EXISTS (SELECT * FROM HOADON WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI AND NGAYGIAODICH IS NULL)
		BEGIN
			PRINT 'DON THUOC DA THANH TOAN KHONG THE THEM'
			ROLLBACK TRAN
			RETURN 1
		END

		DECLARE @TIEN FLOAT
		SET @TIEN = (SELECT GIATHUOC * @SOLUONG FROM THUOC WHERE IDTHUOC = @IDTHUOC)

		--WAITFOR DELAY '0:0:5'

		UPDATE BUOIDIEUTRI
		SET TONGTIEN = TONGTIEN + @TIEN
		WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI
		
		UPDATE HOADON
		SET TONGTIEN = TONGTIEN + @TIEN
		WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI

	-----ĐỂ TEST
		--WAITFOR DELAY '0:0:10'
		
		INSERT CHITIETDONTHUOC(IDDONTHUOC, IDTHUOC, SOLUONG)
		VALUES (@IDDONTHUOC, @IDTHUOC, @SOLUONG)
	-------
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		SELECT ERROR_MESSAGE() AS ErrorMessage;
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0

GO