--CẬP NHẬT BẢNG CHI TIẾT RĂNG
-- BƯỚC 1:
ALTER TABLE CHITIETRANGDIEUTRI
DROP CONSTRAINT FK_CTRDT_BDT

ALTER TABLE CHITIETRANGDIEUTRI
DROP CONSTRAINT FK_CTRDT_LDT

DELETE FROM CHITIETRANGDIEUTRI
--BƯỚC 2:
ALTER TABLE CHITIETRANGDIEUTRI
ADD CONSTRAINT FK_CTRDT_CTDT
	FOREIGN KEY (IDBUOIDIEUTRI,MADIEUTRI)
	REFERENCES CHITIETDIEUTRI(IDBUOIDIEUTRI,MADIEUTRI)
--BƯỚC 3: vô folder dataInsertion chạy lại file dbo.CHITETRANGDIEUTRI.sql

--CẬP NHẬT LỊCH HẸN
ALTER TABLE LICHHEN
DROP COLUMN VAITRO;

DELETE FROM LICHHEN

--CẬP NHẬT KẾ HOẠCH ĐIÊU TRỊ
ALTER TABLE KEHOACHDIEUTRI
DROP COLUMN	TONGGIA;

--CẬP NHẬT HÓA ĐƠN
ALTER TABLE HOADON
DROP COLUMN TIENDATRA;