USE QLPK_CSDL
GO
--XEM TẤT CẢ LOẠI ÐIỀU TRỊ
--RETURN TABLE: MÃ DANH MỤC, TÊN DANH MỤC, MÃ ÐIỀU TRỊ, TÊN ÐIỀU TRỊ
CREATE FUNCTION LAYTATCADIEUTRI()
RETURNS TABLE
AS
	RETURN (SELECT LDT.MADANHMUC , DM.TENDM , LDT.MADIEUTRI , LDT.TENDIEUTRI  
			FROM LOAIDIEUTRI LDT JOIN DANHMUCDIEUTRI DM ON LDT.MADANHMUC = DM.MADANHMUC)
GO

--LẤY DANH SÁCH BUỔI ĐIỀU TRỊ THEO BỆNH NHÂN - KÈM CHI TIẾT MỖI BUỔI ĐIỀU TRỊ
CREATE OR ALTER PROC LAYBUOIDT_BN
	@MABENHNHAN CHAR(8)
AS
BEGIN TRAN
	BEGIN TRY
		--KIỂM TRA ÐIỀU KIỆN
		IF NOT EXISTS (SELECT HSBN.IDBENHNHAN
						FROM HOSOBENHNHAN HSBN
						WHERE HSBN.IDBENHNHAN = @MABENHNHAN)
			BEGIN
				PRINT N'KHÔNG TÌM THẤY BỆNH NHÂN'
				ROLLBACK TRAN
				RETURN 1
			END
		--THỰC THI
		SELECT *
		FROM BUOIDIEUTRI BDT 
			JOIN CHITIETDIEUTRI CTDT ON BDT.IDBUOIDIEUTRI = CTDT.IDBUOIDIEUTRI 
			JOIN LOAIDIEUTRI LDT ON CTDT.MADIEUTRI = LDT.MADIEUTRI
		WHERE BDT.BNKHAMLE = @MABENHNHAN		
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO


--KHÔNG CẦN
--XEM CHI TIẾT CỦA 1 BUỔI ÐIỀU TRỊ 
--CREATE FUNCTION CHITIETBDT 
--	(@IDBUOIDIEUTRI CHAR(10))
--RETURNS TABLE
--AS
--	RETURN (SELECT*
--			FROM CHITIETDIEUTRI CTDT
--			WHERE CTDT.IDBUOIDIEUTRI = @IDBUOIDIEUTRI)
--GO

--THÊM BUỔI ĐIỀU TRỊ
--THÊM 1 BUỔI ÐIỀU TRỊ - THÔNG TIN TỔNG QUAN
CREATE OR ALTER PROC THEMBUOIDT
	@MABENHNHAN CHAR(8), 
	@IDBUOIDIEUTRI CHAR(10), 
	@MOTA NVARCHAR(100),
	@GHICHU NVARCHAR(100),
	@NGAY DATE,
	@KHAMCHINH CHAR(8),
	@TROKHAM CHAR(8),
	@KEHOACH CHAR(10)
AS
BEGIN TRAN
	BEGIN TRY
		--KIỂM TRA ÐIỀU KIỆN
		IF (@MABENHNHAN IS NULL) OR
			(@IDBUOIDIEUTRI IS NULL) OR
			(@NGAY IS NULL) OR
			(@KHAMCHINH IS NULL) OR
			(@TROKHAM IS NULL)
			BEGIN 
				PRINT N'THIẾU TRƯỜNG CẦN THIẾT'
				ROLLBACK TRAN
				RETURN 1
			END
		IF (@KHAMCHINH = @TROKHAM)
			BEGIN
				PRINT N'KHÁM CHÍNH KO ÐUỢC GIỐNG TRỢ KHÁM'
				ROLLBACK TRAN
				RETURN 1
			END
		--THỰC THI
		INSERT BUOIDIEUTRI (IDBUOIDIEUTRI, BNKHAMLE, MOTABDT, GHICHUBDT, NGAYDT, KHAMCHINH, TROKHAM, KEHOACHDT)
		VALUES 
			(@IDBUOIDIEUTRI, @MABENHNHAN, @MOTA, @GHICHU, @NGAY, @KHAMCHINH, @TROKHAM, @KEHOACH)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO

--THÊM CHI TIẾT BUỔI ÐIỀU TRỊ
CREATE OR ALTER PROC THEMCHITIETDT
	@MADIEUTRI CHAR(5),
	@IDBUOIDIEUTRI CHAR(10)
AS
BEGIN TRAN
	BEGIN TRY
		--KIỂM TRA ÐIỀU KIỆN
		IF (@MADIEUTRI IS NULL) OR (@IDBUOIDIEUTRI IS NULL)
			BEGIN 
				PRINT N'THIẾU TRƯỜNG CẦN THIẾT'
				ROLLBACK TRAN
				RETURN 1
			END

		DECLARE @NGAY1 DATE;
		(SELECT @NGAY1 = NGAYDT FROM BUOIDIEUTRI BDT WHERE BDT.IDBUOIDIEUTRI = @IDBUOIDIEUTRI)
		IF (@NGAY1 < GETDATE()) 
			BEGIN 
				PRINT N'BUỔI ĐIỀU TRỊ ĐÃ XẢY RA KHÔNG THỂ CHỈNH SỬA';
				ROLLBACK TRAN
				RETURN 1
			END

		--THỰC THI
		INSERT CHITIETDIEUTRI(MADIEUTRI,IDBUOIDIEUTRI)
		VALUES
			(@MADIEUTRI, @IDBUOIDIEUTRI)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO

--THÊM THÔNG TIN RĂNG ĐIỀU TRỊ
CREATE OR ALTER PROC THEMRANGDT
	@MADIEUTRI CHAR(5),
	@IDBUOIDIEUTRI CHAR(10),
	@TENRANG NCHAR(20),
	@MATDIEUTRI CHAR(1)
AS
BEGIN TRAN
	BEGIN TRY
		--KIỂM TRA ÐIỀU KIỆN
		IF (@MADIEUTRI IS NULL) OR 
			(@IDBUOIDIEUTRI IS NULL) OR 
			(@TENRANG IS NULL) OR
			(@MATDIEUTRI IS NULL)
			BEGIN 
				PRINT N'THIẾU TRƯỜNG CẦN THIẾT'
				ROLLBACK TRAN
				RETURN 1
			END

		DECLARE @NGAY1 DATE;
		(SELECT @NGAY1 = NGAYDT FROM BUOIDIEUTRI BDT WHERE BDT.IDBUOIDIEUTRI = @IDBUOIDIEUTRI)
		IF (@NGAY1 < GETDATE()) 
			BEGIN 
				PRINT N'BUỔI ĐIỀU TRỊ ĐÃ XẢY RA KHÔNG THỂ CHỈNH SỬA';
				ROLLBACK TRAN
				RETURN 1
			END

		--THỰC THI
		INSERT CHITIETRANGDIEUTRI(MADIEUTRI,IDBUOIDIEUTRI, TENRANG, MATDIEUTRI)
		VALUES
			(@MADIEUTRI, @IDBUOIDIEUTRI, @TENRANG, @MATDIEUTRI)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO

--XÓA BUỔI ĐIỀU TRỊ
--XÓA BUỔI ĐIỀU TRỊ - NẾU MÀ NGÀY ĐIỀU TRỊ CHƯA XẢY RA
CREATE OR ALTER PROC XOABUOIDT
	@IDBUOIDIEUTRI CHAR(10)
AS
BEGIN TRAN
	BEGIN TRY
		--KIỂM TRA ÐIỀU KIỆN
		IF (@IDBUOIDIEUTRI IS NULL)
			BEGIN 
				PRINT N'THIẾU TRƯỜNG CẦN THIẾT'
				ROLLBACK TRAN
				RETURN 1
			END
		
		DECLARE @NGAY1 DATE;
		(SELECT @NGAY1 = NGAYDT FROM BUOIDIEUTRI BDT WHERE BDT.IDBUOIDIEUTRI = @IDBUOIDIEUTRI)
		IF (@NGAY1 < GETDATE()) 
			BEGIN 
				PRINT N'BUỔI ĐIỀU TRỊ ĐÃ XẢY RA KHÔNG THỂ XÓA';
				ROLLBACK TRAN
				RETURN 1
			END

		--THỰC THI
		DELETE 
			FROM CHITIETRANGDIEUTRI 
			WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI
		DELETE
			FROM CHITIETDIEUTRI
			WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI
		DELETE
			FROM BUOIDIEUTRI
			WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO

--CHỈNH SỬA BUỔI ĐIỀU TRỊ
--CẬP NHẬT THÔNG TIN TỔNG QUAN BUỔI ÐIỀU TRỊ
CREATE OR ALTER PROC UPDATEBUOIDT
	@MABENHNHAN CHAR(8), 
	@IDBUOIDIEUTRI CHAR(10), 
	@MOTA NVARCHAR(100),
	@GHICHU NVARCHAR(100),
	@NGAY DATE,
	@KHAMCHINH CHAR(8),
	@TROKHAM CHAR(8),
	@KEHOACH CHAR(10)
AS
BEGIN TRAN
	BEGIN TRY
		--KIỂM TRA ÐIỀU KIỆN
		IF (@IDBUOIDIEUTRI IS NULL)
		BEGIN 
			PRINT N'THIẾU TRƯỜNG CẦN THIẾT - IDBUOIDIEUTRI'
			ROLLBACK TRAN
			RETURN 1
		END
		
		DECLARE @NGAY1 DATE;
		(SELECT @NGAY1 = NGAYDT FROM BUOIDIEUTRI BDT WHERE BDT.IDBUOIDIEUTRI = @IDBUOIDIEUTRI)
		IF (@NGAY1 < GETDATE()) 
			BEGIN 
				PRINT N'BUỔI ĐIỀU TRỊ ĐÃ XẢY RA KHÔNG THỂ CHỈNH SỬA';
				ROLLBACK TRAN
				RETURN 1
			END
		--THỰC THI
		UPDATE BUOIDIEUTRI
		SET BNKHAMLE = @MABENHNHAN, MOTABDT = @MOTA, GHICHUBDT = @GHICHU, NGAYDT = @NGAY, KHAMCHINH = @KHAMCHINH, TROKHAM = @TROKHAM, KEHOACHDT = @KEHOACH
		WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI

	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN 
RETURN 0
GO

--XÓA CTDT ĐIỀU TRỊ CŨ THÊM CTDT MỚI
CREATE OR ALTER PROC THEMCHITIETDT
	@MADIEUTRI CHAR(5),
	@IDBUOIDIEUTRI CHAR(10)
AS
BEGIN TRAN
	BEGIN TRY
		--KIỂM TRA ÐIỀU KIỆN
		IF (@MADIEUTRI IS NULL) OR 
			(@IDBUOIDIEUTRI IS NULL)
			BEGIN 
				PRINT N'THIẾU TRƯỜNG CẦN THIẾT'
				ROLLBACK TRAN
				RETURN 1
			END

		DECLARE @NGAY1 DATE;
		(SELECT @NGAY1 = NGAYDT FROM BUOIDIEUTRI BDT WHERE BDT.IDBUOIDIEUTRI = @IDBUOIDIEUTRI)
		IF (@NGAY1 < GETDATE()) 
			BEGIN 
				PRINT N'BUỔI ĐIỀU TRỊ ĐÃ XẢY RA KHÔNG THỂ CHỈNH SỬA';
				ROLLBACK TRAN
				RETURN 1
			END

		--THỰC THI
		DELETE 
			FROM CHITIETRANGDIEUTRI
			WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI AND MADIEUTRI = @MADIEUTRI
		DELETE 
			FROM CHITIETDIEUTRI
			WHERE MADIEUTRI = @MADIEUTRI AND IDBUOIDIEUTRI = @IDBUOIDIEUTRI

	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO

--CHỈNH SỬA CHI TIẾT RĂNG ĐIỀU TRỊ --XÓA
