
CREATE OR ALTER PROC SP_XEMDANHSACHDONTHUOCBN 
	@IDBENHNHAN CHAR(8)
AS
BEGIN TRAN
	BEGIN TRY
	SELECT DT.IDDONTHUOC, DT.NGAYCAP, DT.IDBUOIDIEUTRI, BN.TENBN, SUM(CT.SOLUONG * T.GIATHUOC) AS 'GIA'
	FROM DONTHUOC DT, CHITIETDONTHUOC CT, THUOC T, BUOIDIEUTRI BDT, HOSOBENHNHAN BN
	WHERE CT.IDTHUOC = T.IDTHUOC AND BDT.BNKHAMLE = @IDBENHNHAN AND BDT.IDBUOIDIEUTRI = DT.IDBUOIDIEUTRI AND DT.IDDONTHUOC = CT.IDDONTHUOC AND BN.IDBENHNHAN=@IDBENHNHAN
	GROUP BY DT.IDDONTHUOC, DT.NGAYCAP, DT.IDBUOIDIEUTRI, BN.TENBN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage;
		ROLLBACK TRAN
		RETURN 2
	END CATCH
COMMIT TRAN
RETURN 0
GO

CREATE OR ALTER PROC SP_XEMCHITIETDONTHUOC 
	@IDDONTHUOC CHAR(12)
AS
BEGIN TRAN
	BEGIN TRY
	DECLARE @TONGGIA FLOAT
	SET @TONGGIA = (SELECT SUM(T.GIATHUOC * CT.SOLUONG) FROM CHITIETDONTHUOC CT JOIN THUOC T ON CT.IDTHUOC = T.IDTHUOC WHERE CT.IDDONTHUOC = @IDDONTHUOC GROUP BY CT.IDDONTHUOC)
	SELECT CT.IDTHUOC , T.TENTHUOC, CT.SOLUONG, T.GIATHUOC * CT.SOLUONG as 'GIA', @TONGGIA 'TONGGIA'
	FROM CHITIETDONTHUOC CT, THUOC T, DONTHUOC D
	WHERE D.IDDONTHUOC = @IDDONTHUOC AND CT.IDDONTHUOC = D.IDDONTHUOC AND T.IDTHUOC = CT.IDTHUOC
	
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage;
		ROLLBACK TRAN
		RETURN 2
	END CATCH
COMMIT TRAN
RETURN 0
GO

CREATE OR ALTER PROC SP_THEMDONTHUOC 
	@IDDONTHUOC CHAR(12),
	@NGAYCAP DATE,
	@IDBUOIDIEUTRI CHAR(10)
AS
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS (SELECT * FROM BUOIDIEUTRI WHERE IDBUOIDIEUTRI=@IDBUOIDIEUTRI)
	BEGIN
		ROLLBACK TRAN
		RETURN 1
	END
	INSERT DONTHUOC (IDDONTHUOC,NGAYCAP,IDBUOIDIEUTRI)
	VALUES (@IDDONTHUOC, @NGAYCAP, @IDBUOIDIEUTRI)
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage;
		ROLLBACK TRAN
		RETURN 2
	END CATCH
COMMIT TRAN
RETURN 0
GO

CREATE OR ALTER PROC SP_THEMCHITIETDONTHUOC 
	@IDTHUOC CHAR(8),
	@IDDONTHUOC CHAR(12),
	@SOLUONG INT
AS
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS (SELECT * FROM THUOC WHERE IDTHUOC = @IDTHUOC)
	BEGIN
		ROLLBACK TRAN
		RETURN 1
	END
	IF NOT EXISTS (SELECT * FROM DONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC)
	BEGIN
		ROLLBACK TRAN
		RETURN 1
	END
	INSERT CHITIETDONTHUOC(IDTHUOC, IDDONTHUOC, SOLUONG)
	VALUES (@IDTHUOC, @IDDONTHUOC, @SOLUONG)
	
	DECLARE @IDBUOIDIEUTRI CHAR(10)
	SET @IDBUOIDIEUTRI = (SELECT IDBUOIDIEUTRI FROM DONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC)

	DECLARE @GIA FLOAT
	DECLARE @GIATHUOC FLOAT
	SET @GIATHUOC = (SELECT GIATHUOC FROM THUOC WHERE IDTHUOC=@IDTHUOC)
	SET @GIA = @SOLUONG * @GIATHUOC
	DECLARE @TONGGIA FLOAT
	SET @TONGGIA = (SELECT TONGTIEN FROM BUOIDIEUTRI WHERE IDBUOIDIEUTRI=@IDBUOIDIEUTRI)
	SET @TONGGIA = @TONGGIA + @GIA
	UPDATE BUOIDIEUTRI
	SET TONGTIEN = @TONGGIA
	WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI
	--END TRY
	
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage;
		ROLLBACK TRAN
		RETURN 2
	END CATCH
COMMIT TRAN
RETURN 0
GO

CREATE OR ALTER PROC SP_XOADONTHUOC
	@IDDONTHUOC CHAR(12)
AS
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS (SELECT * FROM DONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC)
	BEGIN
		ROLLBACK TRAN
		RETURN 1
	END
	DECLARE @IDBUOIDIEUTRI char(10)
	SET @IDBUOIDIEUTRI = (SELECT IDBUOIDIEUTRI FROM DONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC)

	IF EXISTS (SELECT * FROM HOADON WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI)
	BEGIN 
		PRINT 'DON THUOC DA THANH TOAN KHONG THE XOA'
		ROLLBACK TRAN
		RETURN 1
	END

	DECLARE @TONGDONTHUOC FLOAT
	SET @TONGDONTHUOC = (SELECT SUM(T.GIATHUOC * CT.SOLUONG) FROM THUOC T JOIN CHITIETDONTHUOC CT ON CT.IDTHUOC = T.IDTHUOC WHERE CT.IDDONTHUOC = @IDDONTHUOC GROUP BY CT.IDDONTHUOC)

	UPDATE BUOIDIEUTRI
	SET TONGTIEN = TONGTIEN - @TONGDONTHUOC
	WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI

	DELETE CHITIETDONTHUOC
	WHERE IDDONTHUOC = @IDDONTHUOC
	
	DELETE DONTHUOC
	WHERE IDDONTHUOC = @IDDONTHUOC

	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage;
		ROLLBACK TRAN
		RETURN 2
	END CATCH
COMMIT TRAN
RETURN 0
GO


CREATE OR ALTER PROC SP_XOACHITIETDONTHUOC
	@IDTHUOC CHAR(8),
	@IDDONTHUOC CHAR(12)
AS 
BEGIN TRAN
	BEGIN TRY
	DECLARE @TIENTHUOC FLOAT
	SET @TIENTHUOC = (SELECT CT.SOLUONG * T.GIATHUOC FROM CHITIETDONTHUOC CT JOIN THUOC T ON CT.IDTHUOC = T.IDTHUOC WHERE CT.IDTHUOC = @IDTHUOC AND CT.IDDONTHUOC=@IDDONTHUOC)
	DECLARE @IDBUOIDIEUTRI CHAR(10)
	SET @IDBUOIDIEUTRI = (SELECT IDBUOIDIEUTRI FROM DONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC)
	UPDATE BUOIDIEUTRI	
	SET TONGTIEN = TONGTIEN - @TIENTHUOC
	WHERE IDBUOIDIEUTRI = @IDBUOIDIEUTRI

	DELETE CHITIETDONTHUOC WHERE IDDONTHUOC = @IDDONTHUOC AND IDTHUOC=@IDTHUOC
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage;
		ROLLBACK TRAN
		RETURN 2
	END CATCH
COMMIT TRAN
RETURN 0
GO
