USE QLPK_CSDL
GO

--XEM THÔNG TIN CÁ NHÂN HỒ SƠ BỆNH NHÂN CÓ BÁC SĨ MẶC ĐỊNH
GO
CREATE OR ALTER PROC xemchitiethosobenhnhan @IDNguoiDung CHAR(8)
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			IF (@IDNguoiDung IS NULL)
			BEGIN
				PRINT N'KHÔNG TÌM THẤY NGƯỜI DÙNG'
				ROLLBACK TRAN
				RETURN;
			END
			DECLARE @TONGTIENDATRA FLOAT
			SELECT @TONGTIENDATRA = SUM(TONGTIEN)
			FROM HOADON HD
			WHERE HD.IDBENHNHAN = @IDNguoiDung
			GROUP BY HD.IDBENHNHAN

			DECLARE @TONGTIENDIEUTRI FLOAT
			SELECT @TONGTIENDIEUTRI = SUM(BDT.TONGTIEN)
			FROM BUOIDIEUTRI BDT
			WHERE BDT.BNKHAMLE = @IDNguoiDung
			GROUP BY BDT.BNKHAMLE

			SELECT BN.*, NV.TENNV, @TONGTIENDIEUTRI AS TONGTIENDIEUTRI, @TONGTIENDATRA AS TONGTIENDATRA
			FROM HOSOBENHNHAN BN
				JOIN NHANVIEN NV
			ON NV.IDNHANVIEN = BN.BACSIMD 
			WHERE BN.IDBENHNHAN = @IDNguoiDung
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN;
	END CATCH
END
GO
EXEC xemchitiethosobenhnhan 'BN000001'
GO
CREATE OR ALTER PROC timhosobenhnhanquaten @TEN NVARCHAR(50)
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			IF (@TEN IS NULL)
			BEGIN
				PRINT N'KHÔNG CÓ THÔNG TIN TÌM KIẾM'
				ROLLBACK TRAN
				RETURN;
			END
			SELECT *
			FROM HOSOBENHNHAN BN
			WHERE BN.TENBN LIKE '%' + @TEN + '%'
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK
	END CATCH
END
GO
EXEC timhosobenhnhanquaten 'toan ti phu'
GO
--CẬP NHẬT HỒ SƠ BỆNH NHÂN
CREATE OR ALTER PROC capnhathosobenhnhan 
		@IDBENHNHAN CHAR(8), 
		@TENBN NVARCHAR(50),
		@IDPHONGKHAM CHAR(3),
		@NAMSINH DATE,
		@GIOITINH NVARCHAR(3),
		@TUOI INT,
		@SDT CHAR(10),
		@EMAIL VARCHAR(50), 
		@DIACHI NVARCHAR(200),
		@MATKHAU VARCHAR(10),
		@BACSIMD CHAR(8),
		@TTTQ NVARCHAR(100),
		@TTDU NVARCHAR(100),
		@THUOCCHONGCD NVARCHAR(30)
AS
BEGIN TRAN
	BEGIN TRY
	IF (@IDBENHNHAN IS NULL)
	BEGIN
		PRINT N'THIẾU TRƯỜNG THÔNG TIN'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@TENBN IS NULL)
	BEGIN
		PRINT N'HỌ TÊN BỆNH NHÂN KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@IDPHONGKHAM IS NULL)
	BEGIN
		PRINT N'ID PHÒNG KHÁM KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@NAMSINH IS NULL)
	BEGIN
		PRINT N'NĂM SINH KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@GIOITINH IS NULL)
	BEGIN
		PRINT N'GIỚI TÍNH KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@TUOI IS NULL)
	BEGIN
		PRINT N'TUỔI KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@SDT IS NULL)
	BEGIN
		PRINT N'SỐ ĐIỆN THOẠI KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@DIACHI IS NULL)
	BEGIN
		PRINT N'ĐỊA CHỈ KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
		UPDATE HOSOBENHNHAN
		SET TENBN = @TENBN, IDPHONGKHAM = @IDPHONGKHAM, NAMSINHBN = @NAMSINH, GIOITINHBN = @GIOITINH, TUOI = @TUOI, SODIENTHOAIBN = @SDT,
			EMAIL = @EMAIL, DIACHI = @DIACHI, MATKHAU = @MATKHAU, BACSIMD = @BACSIMD, TTTONGQUAN = @TTTQ, TINHTRANGDIUNG = @TTDU, 
			THUOCCHONGCHIDINH = @THUOCCHONGCD
		WHERE @IDBENHNHAN = IDBENHNHAN
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
	END CATCH
COMMIT TRAN

