USE QLPK_CSDL
GO

Create function UDF_ExtractNumbers
(  
  @input CHAR(8)  
)  
Returns CHAR(8)  
As  
Begin  
  Declare @alphabetIndex int = Patindex('%[^0-9]%', @input)  
  Begin  
    While @alphabetIndex > 0  
    Begin  
      Set @input = Stuff(@input, @alphabetIndex, 1, '' )  
      Set @alphabetIndex = Patindex('%[^0-9]%', @input )  
    End  
  End  
  Return @input
End

GO
--CẬP NHẬT HỒ SƠ BỆNH NHÂN
CREATE OR ALTER PROC capnhathosobenhnhan 
		@IDBENHNHAN CHAR(8), 
		@TENBN NVARCHAR(50),
		@IDPHONGKHAM CHAR(3),
		@NAMSINH DATE,
		@GIOITINH NVARCHAR(3),
		@TUOI INT,
		@SDT CHAR(10),
		@EMAIL VARCHAR(50), 
		@DIACHI NVARCHAR(200),
		@MATKHAU VARCHAR(10),
		@BACSIMD CHAR(8),
		@TTTQ NVARCHAR(100),
		@TTDU NVARCHAR(100),
		@THUOCCHONGCD NVARCHAR(30)
AS
BEGIN TRAN
	BEGIN TRY
	IF (@IDBENHNHAN IS NULL)
	BEGIN
		PRINT N'THIẾU TRƯỜNG THÔNG TIN'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@TENBN IS NULL)
	BEGIN
		PRINT N'HỌ TÊN BỆNH NHÂN KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@IDPHONGKHAM IS NULL)
	BEGIN
		PRINT N'ID PHÒNG KHÁM KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@NAMSINH IS NULL)
	BEGIN
		PRINT N'NĂM SINH KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@GIOITINH IS NULL)
	BEGIN
		PRINT N'GIỚI TÍNH KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@TUOI IS NULL)
	BEGIN
		PRINT N'TUỔI KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@SDT IS NULL)
	BEGIN
		PRINT N'SỐ ĐIỆN THOẠI KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	IF (@DIACHI IS NULL)
	BEGIN
		PRINT N'ĐỊA CHỈ KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
		UPDATE HOSOBENHNHAN
		SET TENBN = @TENBN, IDPHONGKHAM = @IDPHONGKHAM, NAMSINHBN = @NAMSINH, GIOITINHBN = @GIOITINH, TUOI = @TUOI, SODIENTHOAIBN = @SDT,
			EMAIL = @EMAIL, DIACHI = @DIACHI, MATKHAU = @MATKHAU, BACSIMD = @BACSIMD, TTTONGQUAN = @TTTQ, TINHTRANGDIUNG = @TTDU, 
			THUOCCHONGCHIDINH = @THUOCCHONGCD
		WHERE @IDBENHNHAN = IDBENHNHAN
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
	END CATCH
COMMIT TRAN

GO
--THÊM MỚI HỒ SƠ BỆNH NHÂN
CREATE OR ALTER PROC themmoihosobenhnhan 
		@TENBN NVARCHAR(50),
		@IDPHONGKHAM CHAR(3),
		@NAMSINH DATE,
		@GIOITINH NVARCHAR(3),
		@TUOI INT,
		@SDT CHAR(10),
		@EMAIL VARCHAR(50), 
		@DIACHI NVARCHAR(200),
		@MATKHAU VARCHAR(10),
		@BACSIMD CHAR(8),
		@TTTQ NVARCHAR(100),
		@TTDU NVARCHAR(100),
		@THUOCCHONGCD NVARCHAR(30)
AS 
BEGIN TRAN
	BEGIN TRY 
		IF (@TENBN IS NULL)
		BEGIN
			PRINT N'HỌ TÊN BỆNH NHÂN KHÔNG ĐƯỢC ĐỂ TRỐNG'
			ROLLBACK TRAN
			RETURN;
		END
		IF (@IDPHONGKHAM IS NULL)
		BEGIN
			PRINT N'ID PHÒNG KHÁM KHÔNG ĐƯỢC ĐỂ TRỐNG'
			ROLLBACK TRAN
			RETURN;
		END
		IF (@NAMSINH IS NULL)
		BEGIN
			PRINT N'NĂM SINH KHÔNG ĐƯỢC ĐỂ TRỐNG'
			ROLLBACK TRAN
			RETURN;
		END
		IF (@GIOITINH IS NULL)
		BEGIN
			PRINT N'GIỚI TÍNH KHÔNG ĐƯỢC ĐỂ TRỐNG'
			ROLLBACK TRAN
			RETURN;
		END
		IF (@TUOI IS NULL)
		BEGIN
			PRINT N'TUỔI KHÔNG ĐƯỢC ĐỂ TRỐNG'
			ROLLBACK TRAN
			RETURN;
		END
		IF (@SDT IS NULL)
		BEGIN
			PRINT N'SỐ ĐIỆN THOẠI KHÔNG ĐƯỢC ĐỂ TRỐNG'
			ROLLBACK TRAN
			RETURN;
		END
		IF (@DIACHI IS NULL)
		BEGIN
			PRINT N'ĐỊA CHỈ KHÔNG ĐƯỢC ĐỂ TRỐNG'
			ROLLBACK TRAN
			RETURN;
		END

		--DECLARE @LASTID CHAR(8)
		--SELECT TOP 1 @LASTID = IDBENHNHAN FROM HOSOBENHNHAN ORDER BY IDBENHNHAN DESC
		--DECLARE @ID CHAR(8)
		--SELECT @ID = UDF_ExtractNumbers(@LASTID) + 1

		INSERT INTO HOSOBENHNHAN(IDBENHNHAN, TENBN, IDPHONGKHAM, NAMSINHBN, GIOITINHBN, TUOI, SODIENTHOAIBN, EMAIL, DIACHI, MATKHAU, BACSIMD, TTTONGQUAN, TINHTRANGDIUNG, THUOCCHONGCHIDINH)
			VALUES  ('BN100001', @TENBN, @IDPHONGKHAM, @NAMSINH, @GIOITINH, @TUOI, @SDT, @EMAIL, @DIACHI, @MATKHAU, @BACSIMD, @TTTQ, @TTDU, @THUOCCHONGCD)
	END TRY
	BEGIN CATCH 
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK;
		RETURN;
	END CATCH
COMMIT TRAN