USE QLPK_CSDL
GO


GO
--CẬP NHẬT HỒ SƠ BỆNH NHÂN
CREATE OR ALTER PROC capnhathosobenhnhan 
		@IDBENHNHAN CHAR(8), 
		@TENBN NVARCHAR(50),
		@IDPHONGKHAM CHAR(3),
		@NAMSINH DATE,
		@GIOITINH NVARCHAR(3),
		@TUOI INT,
		@SDT CHAR(10),
		@EMAIL VARCHAR(50), 
		@DIACHI NVARCHAR(200),
		@MATKHAU VARCHAR(10),
		@BACSIMD CHAR(8),
		@TTTQ NVARCHAR(100),
		@TTDU NVARCHAR(100),
		@THUOCCHONGCD NVARCHAR(30),
		@DATHANHTOAN FLOAT
AS
BEGIN TRAN
	BEGIN TRY
	IF (@IDBENHNHAN IS NULL)
	BEGIN
		PRINT N'THIẾU TRƯỜNG THÔNG TIN'
		ROLLBACK TRAN
		RETURN;
	END
	ELSE 
	BEGIN
		UPDATE HOSOBENHNHAN
		SET IDBENHNHAN = @IDBENHNHAN
	END
	IF (@TENBN IS NULL)
	BEGIN
		PRINT N'HỌ TÊN BỆNH NHÂN KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	ELSE 
	BEGIN
		UPDATE HOSOBENHNHAN
		SET TENBN = @TENBN
	END
	IF (@IDPHONGKHAM IS NULL)
	BEGIN
		PRINT N'ID PHÒNG KHÁM KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	ELSE 
	BEGIN
		UPDATE HOSOBENHNHAN
		SET IDPHONGKHAM = @IDPHONGKHAM
	END
	IF (@NAMSINH IS NULL)
	BEGIN
		PRINT N'NĂM SINH KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	ELSE 
	BEGIN
		UPDATE HOSOBENHNHAN
		SET NAMSINHBN = @NAMSINH
	END
	IF (@GIOITINH IS NULL)
	BEGIN
		PRINT N'GIỚI TÍNH KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	ELSE 
	BEGIN
		UPDATE HOSOBENHNHAN
		SET GIOITINHBN = @GIOITINH
	END
	IF (@TUOI IS NULL)
	BEGIN
		PRINT N'TUỔI KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	ELSE 
	BEGIN
		UPDATE HOSOBENHNHAN
		SET TUOI = @TUOI
	END
	IF (@SDT IS NULL)
	BEGIN
		PRINT N'SỐ ĐIỆN THOẠI KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	ELSE 
	BEGIN
		UPDATE HOSOBENHNHAN
		SET SODIENTHOAIBN = @SDT
	END
	IF (@DIACHI IS NULL)
	BEGIN
		PRINT N'ĐỊA CHỈ KHÔNG ĐƯỢC ĐỂ TRỐNG'
		ROLLBACK TRAN
		RETURN;
	END
	ELSE 
	BEGIN
		UPDATE HOSOBENHNHAN
		SET DIACHI = @DIACHI
	END
		UPDATE HOSOBENHNHAN
		SET BACSIMD = @BACSIMD
		WHERE @IDBENHNHAN = IDBENHNHAN
		UPDATE HOSOBENHNHAN
		SET EMAIL = @EMAIL
		WHERE @IDBENHNHAN = IDBENHNHAN
		UPDATE HOSOBENHNHAN
		SET MATKHAU = @MATKHAU
		WHERE @IDBENHNHAN = IDBENHNHAN
		UPDATE HOSOBENHNHAN
		SET TTTONGQUAN = @TTTQ
		WHERE @IDBENHNHAN = IDBENHNHAN
		UPDATE HOSOBENHNHAN
		SET TINHTRANGDIUNG = @TTDU
		WHERE @IDBENHNHAN = IDBENHNHAN
		UPDATE HOSOBENHNHAN
		SET THUOCCHONGCHIDINH = @THUOCCHONGCD
		WHERE @IDBENHNHAN = IDBENHNHAN
		UPDATE HOSOBENHNHAN
		SET DATHANHTOAN = @DATHANHTOAN
		WHERE @IDBENHNHAN = IDBENHNHAN
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
	END CATCH
COMMIT TRAN

