---------------------------------------------------TOOLS
--XEM CLUSTERED INDEX CỦA TỪNG BẢNG
EXEC sp_helpindex 'LICHLAMVIEC'

--XEM ĐỀ XUẤT INDEX CỦA DBMS
SELECT * FROM sys.dm_db_missing_index_details

--XÓA PLANCACHE PROCEDURE
EXEC sp_recompile 'LAYBUOIDT_BN'

--XÓA INDEX
DROP INDEX LICHHEN_NGAYHEN
ON LICHHEN;

---------------------------------------------------TẠO INDEX
--LỊCH HẸN
CREATE NONCLUSTERED INDEX LICHHEN_NGAYHEN
ON LICHHEN (NGAYHEN DESC)

--ĐIỀU TRỊ
CREATE NONCLUSTERED INDEX BDT_BN
ON BUOIDIEUTRI (BNKHAMLE DESC)

CREATE NONCLUSTERED INDEX BDT_KH
ON BUOIDIEUTRI ( KEHOACHDT DESC)

--ĐƠN THUỐC
CREATE NONCLUSTERED INDEX DT_BDT
ON DONTHUOC (IDBUOIDIEUTRI DESC)

--KHÔNG TẠO
--CREATE NONCLUSTERED INDEX BDT_NGAY
--ON BUOIDIEUTRI (NGAYDT DESC)