---------------------------------------------------TOOLS
--XEM CLUSTERED INDEX CỦA TỪNG BẢNG
EXEC sp_helpindex 'LICHLAMVIEC'

--XEM ĐỀ XUẤT INDEX CỦA DBMS
SELECT * FROM sys.dm_db_missing_index_details

--XÓA PLANCACHE PROCEDURE
EXEC sp_recompile 'timhosobenhnhanquaten'

--XÓA INDEX
--LICH HEN
DROP INDEX LICHHEN_NGAYHEN
ON LICHHEN;

DROP INDEX LICHHEN_PHONGKHAM_NGAYHEN
ON LICHHEN;

DROP INDEX KH_BENHNHAN
ON BUOIDIEUTRI;

--ĐIỀU TRỊ
DROP INDEX BDT_NGAY
ON BUOIDIEUTRI;

DROP INDEX BDT_BN_NGAY
ON BUOIDIEUTRI;

DROP INDEX BDT_KH1
ON BUOIDIEUTRI;

DROP INDEX KH_BENHNHAN
ON KEHOACHDIEUTRI;

DROP INDEX DT_BDT
ON DONTHUOC;

DROP INDEX CTDT_DT
ON CHITIETDONTHUOC;

DROP INDEX HD_BDT
ON HOADON

DROP INDEX HD_BN
ON HOADON

DROP INDEX HS_TEN
ON HOSOBENHNHAN


---------------------------------------------------TẠO INDEX
--LỊCH HẸN

CREATE NONCLUSTERED INDEX LICHHEN_BENHNHAN_NGAYHEN
ON LICHHEN (BENHNHAN DESC, NGAYHEN DESC)

CREATE NONCLUSTERED INDEX LICHHEN_PHONGKHAM_NGAYHEN
ON LICHHEN (PHONG DESC, NGAYHEN DESC)

CREATE NONCLUSTERED INDEX LICHHEN_NGAYHEN
ON LICHHEN (NGAYHEN DESC)

--ĐIỀU TRỊ
CREATE NONCLUSTERED INDEX BDT_BN_NGAY
ON BUOIDIEUTRI (BNKHAMLE DESC,NGAYDT DESC)

CREATE NONCLUSTERED INDEX BDT_NGAY
ON BUOIDIEUTRI (NGAYDT DESC)

CREATE NONCLUSTERED INDEX BDT_KH
ON BUOIDIEUTRI ( KEHOACHDT DESC)

CREATE NONCLUSTERED INDEX KH_BENHNHAN
ON KEHOACHDIEUTRI (BENHNHAN DESC)

--ĐƠN THUỐC
CREATE NONCLUSTERED INDEX DT_BDT
ON DONTHUOC (IDBUOIDIEUTRI DESC)

--CREATE NONCLUSTERED INDEX CTDT_DT
--ON CHITIETDONTHUOC (IDDONTHUOC DESC, IDTHUOC DESC)


--HÓA ĐƠN
CREATE NONCLUSTERED INDEX HD_BDT
ON HOADON (IDBUOIDIEUTRI DESC)

CREATE NONCLUSTERED INDEX HD_BN
ON HOADON (IDBENHNHAN DESC)

--HỒ SƠ BỆNH NHÂN
CREATE NONCLUSTERED INDEX HS_TEN
ON HOSOBENHNHAN (TENBN DESC)

--KHÔNG TẠO
--CREATE NONCLUSTERED INDEX BDT_NGAY
--ON BUOIDIEUTRI (NGAYDT DESC)