--LICHHEN--
-- Xem danh sách lịch hẹn của 1 bệnh nhân theo ngày
CREATE OR ALTER PROC SP_XEM_LICH_HEN_BN
	@ID_BENHNHAN CHAR(8),
	@NGAY DATE
AS
SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS
		(
			SELECT *
			FROM LICHHEN LH
			WHERE LH.BENHNHAN = @ID_BENHNHAN AND LH.NGAYHEN = @NGAY
		)
		BEGIN
			RAISERROR(N'Lịch hẹn không tồn tại',16,1)
			ROLLBACK TRAN
			RETURN 1
		END
		
		--ĐỂ TEST
		WAITFOR DELAY '0:0:5'
		----------
		SELECT BN.TENBN, BN.IDBENHNHAN, LH.NGAYHEN, LH.THOIGIANHEN, LH.TINHTRANG, LH.PHONG, LH.GHICHULICHHEN, LH.BACSI, LH.TROKHAM
		FROM LICHHEN LH
		JOIN HOSOBENHNHAN BN ON LH.BENHNHAN = BN.IDBENHNHAN
		WHERE BN.IDBENHNHAN = @ID_BENHNHAN AND LH.NGAYHEN = @NGAY
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS errormessage
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO

-- Cập nhật thông tin lịch hẹn
CREATE OR ALTER PROC SP_CAP_NHAT_TT_LICH_HEN
	@NGAYHEN DATE,
	@THOIGIANHEN TIME,
	@BACSI CHAR(8),
	@BENHNHAN CHAR(8),
	@TINHTRANG_NEW NCHAR(15)

AS
BEGIN TRAN
	BEGIN TRY
		--Kiểm tra lịch hẹn muốn cập nhật có tồn tại không
		IF NOT EXISTS ( SELECT * 
						FROM LICHHEN 
						WHERE @NGAYHEN = NGAYHEN AND @THOIGIANHEN = THOIGIANHEN 
						AND @BENHNHAN = BENHNHAN AND @BACSI = BACSI )
		BEGIN
			RAISERROR(N'Lịch hẹn không tồn tại',16,1)
			ROLLBACK TRAN
			RETURN 1
		END

		-- Cập nhật thông tin lịch hẹn
		UPDATE LICHHEN
		SET
			TINHTRANG = @TINHTRANG_NEW
		WHERE
			NGAYHEN = @NGAYHEN
			AND THOIGIANHEN = @THOIGIANHEN
			AND BENHNHAN = @BENHNHAN
			AND BACSI = @BACSI

	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS errormessage
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO



