-- Function kiểm tra lịch làm việc trùng lặp
CREATE OR ALTER FUNCTION CHECK_LICH_LAM_VIEC_TRUNG_LAP
(
	@IDNHANVIEN CHAR(8),
	@NGAY INT,
	@THANG INT,
	@NAM INT,
	@ID_CALAM CHAR(2),
	@ID_LICHLAM_UNIQUE NVARCHAR(100)
)
RETURNS INT
AS
BEGIN
	DECLARE @COUNT INT
	SET @COUNT = 0

	-- Kiểm tra lịch làm việc trùng lặp
	SELECT @COUNT = COUNT(*)
	FROM LICHLAMVIEC
	WHERE
		IDNHANVIEN = @IDNHANVIEN
		AND NGAY = @NGAY
		AND THANG = @THANG
		AND NAM = @NAM
		AND IDCALAM = @ID_CALAM

	RETURN @COUNT
END
GO
-- 1. Xem danh sách lịch làm việc của 1 bác sĩ trong ngày
CREATE OR ALTER PROC XEM_LICH_LAM_VIEC_NGAY
	@ID_NHASI CHAR(8),
	@NGAY DATE
AS
BEGIN
	SELECT NS.TENNV, NS.IDNHANVIEN, LLV.*
	FROM LICHLAMVIEC LLV
	JOIN NHANVIEN NS ON LLV.IDNHANVIEN = NS.IDNHANVIEN
	WHERE NS.IDNHANVIEN = @ID_NHASI
		AND LLV.NGAY = @NGAY
END
GO
-- 2. Xem danh sách lịch làm việc của 1 bác sĩ trong tuần
CREATE OR ALTER PROC XEM_LICH_LAM_VIEC_TUAN
	@ID_NHASI CHAR(8),
	@TUAN INT,
	@NAM INT
AS
BEGIN
	SELECT NS.TENNV, NS.IDNHANVIEN, LLV.*
	FROM LICHLAMVIEC LLV
	JOIN NHANVIEN NS ON LLV.IDNHANVIEN = NS.IDNHANVIEN
	WHERE NS.IDNHANVIEN = @ID_NHASI
		AND DATEPART(WEEK, DATEFROMPARTS(LLV.NAM, LLV.THANG, LLV.NGAY)) = @TUAN
		AND LLV.NAM = @NAM
END
GO
-- 3. Xem danh sách lịch làm việc của 1 bác sĩ trong tháng
CREATE OR ALTER PROC XEM_LICH_LAM_VIEC_THANG
	@ID_NHASI CHAR(8),
	@THANG INT,
	@NAM INT
AS
BEGIN
	SELECT NS.TENNV, NS.IDNHANVIEN, LLV.*
	FROM LICHLAMVIEC LLV
	JOIN NHANVIEN NS ON LLV.IDNHANVIEN = NS.IDNHANVIEN
	WHERE NS.IDNHANVIEN = @ID_NHASI
		AND LLV.THANG = @THANG
		AND LLV.NAM = @NAM
END
GO
-- 4. Thêm lịch làm việc cho 1 bác sĩ
CREATE OR ALTER PROC THEM_LICH_LAM_VIEC
	@ID_NHANVIEN CHAR(8),
	@NGAY DATE,
	@ID_CALAM CHAR(2)
AS
BEGIN
	DECLARE @ID_LICHLAM NVARCHAR(100)
	SET @ID_LICHLAM = NEWID()

	-- Kiểm tra lịch làm việc trùng lặp
	IF dbo.CHECK_LICH_LAM_VIEC_TRUNG_LAP(@ID_NHANVIEN, DATEPART(DAY, @NGAY), DATEPART(MONTH, @NGAY), DATEPART(YEAR, @NGAY), @ID_CALAM, @ID_LICHLAM) > 0
	BEGIN
		PRINT N'LỊCH LÀM VIỆC BỊ TRÙNG LẶP'
		RETURN 1
	END

	-- Thêm lịch làm việc
	INSERT INTO LICHLAMVIEC (ID_LICHLAM, IDNHANVIEN, NGAY, THANG, NAM, IDCALAM)
	VALUES (@ID_LICHLAM, @ID_NHANVIEN, @NGAY, DATEPART(MONTH, @NGAY), DATEPART(YEAR, @NGAY), @ID_CALAM)

	RETURN 0
END
GO
-- 5. Xóa lịch làm việc cho 1 bác sĩ
CREATE OR ALTER PROC XOA_LICH_LAM_VIEC
	@ID_LICHLAM NVARCHAR(100)
AS
BEGIN
	-- Kiểm tra nếu là ca làm việc từ ngày hiện tại trở về trước
	IF CONVERT(DATE, GETDATE()) > (SELECT NGAY FROM LICHLAMVIEC WHERE ID_LICHLAM = @ID_LICHLAM)
	BEGIN
		PRINT N'KHÔNG THỂ XÓA LỊCH LÀM VIỆC CŨ'
		RETURN 1
	END

	-- Xóa lịch làm việc
	DELETE FROM LICHLAMVIEC WHERE ID_LICHLAM = @ID_LICHLAM

	RETURN 0
END
GO
-- 6. Chỉnh sửa lịch làm việc cho 1 bác sĩ
CREATE OR ALTER PROC CHINH_SUA_LICH_LAM_VIEC
	@ID_LICHLAM NVARCHAR(100),
	@NGAY DATE,
	@ID_CALAM CHAR(2)
AS
BEGIN
	-- Kiểm tra nếu là ca làm việc từ ngày hiện tại trở về trước
	IF CONVERT(DATE, GETDATE()) > (SELECT NGAY FROM LICHLAMVIEC WHERE ID_LICHLAM = @ID_LICHLAM)
	BEGIN
		PRINT N'KHÔNG THỂ CHỈNH SỬA LỊCH LÀM VIỆC CŨ'
		RETURN 1
	END

	-- Kiểm tra lịch làm việc trùng lặp
	IF dbo.CHECK_LICH_LAM_VIEC_TRUNG_LAP((SELECT IDNHANVIEN FROM LICHLAMVIEC WHERE ID_LICHLAM = @ID_LICHLAM), DATEPART(DAY, @NGAY), DATEPART(MONTH, @NGAY), DATEPART(YEAR, @NGAY), @ID_CALAM, @ID_LICHLAM) > 0
	BEGIN
		PRINT N'LỊCH LÀM VIỆC BỊ TRÙNG LẶP'
		RETURN 1
	END

	-- Chỉnh sửa lịch làm việc
	UPDATE LICHLAMVIEC
	SET NGAY = @NGAY,
		IDCALAM = @ID_CALAM
	WHERE ID_LICHLAM = @ID_LICHLAM

	RETURN 0
END
