-- RÀNG BUỘC TOÀN VẸN CỦA LỊCH HẸN
CREATE OR ALTER PROCEDURE SP_THEMLICHHEN
	@NGAYHEN DATE,
	@THOIGIANHEN TIME,
	@TINHTRANG NVARCHAR(10),
	@PHONG CHAR(3),
	@VAITRO CHAR(2),
	@GHICHU NVARCHAR(100),
	@BACSI CHAR(8),
	@BENHNHAN CHAR(8)
AS
BEGIN TRAN

	-- Kiểm tra ràng buộc thời gian
	IF NOT EXISTS (SELECT * FROM LICHLAMVIEC WHERE IDNHANVIEN = @BACSI AND NGAY = DAY(@NGAYHEN) AND THANG = MONTH(@NGAYHEN) AND NAM = YEAR(@NGAYHEN))
	BEGIN
		RAISERROR(N'Không thể thêm lịch hẹn. Nhân viên không có lịch làm việc cho ngày này.', 16, 1)
		ROLLBACK TRAN
		RETURN
	END

	-- Kiểm tra ràng buộc trùng lặp
	IF EXISTS (SELECT * FROM LICHHEN WHERE NGAYHEN = @NGAYHEN AND THOIGIANHEN = @THOIGIANHEN AND BACSI = @BACSI AND TINHTRANG = @TINHTRANG)
	BEGIN
		RAISERROR(N'Không thể thêm lịch hẹn. Lịch hẹn trùng lặp.', 16, 1)
		ROLLBACK TRAN
		RETURN
	END

	-- Kiểm tra ràng buộc số lượng lịch hẹn
	IF EXISTS (SELECT * FROM LICHHEN WHERE NGAYHEN = @NGAYHEN AND THOIGIANHEN = @THOIGIANHEN AND BENHNHAN = @BENHNHAN)
	BEGIN
		RAISERROR(N'Không thể thêm lịch hẹn. Bệnh nhân đã có lịch hẹn trong khung giờ này.', 16, 1)
		ROLLBACK TRAN
		RETURN
	END

	-- Kiểm tra ràng buộc vai trò
	IF NOT EXISTS (SELECT * FROM NHANVIEN WHERE IDNHANVIEN = @BACSI AND (LOAINV = 'BS' OR LOAINV = 'TK'))
	BEGIN
		RAISERROR(N'Không thể thêm lịch hẹn. Vai trò không hợp lệ.', 16, 1)
		ROLLBACK TRAN
		RETURN
	END

	-- Thực hiện thêm lịch hẹn vào bảng
	INSERT INTO LICHHEN (NGAYHEN, THOIGIANHEN, TINHTRANG, PHONG, VAITRO, GHICHULICHHEN, BACSI, BENHNHAN)
	VALUES (@NGAYHEN, @THOIGIANHEN, @TINHTRANG, @PHONG, @VAITRO, @GHICHU, @BACSI, @BENHNHAN)

COMMIT TRAN
GO

--RÀNG BUỘC TOÀN VẸN CỦA LỊCH LÀM VIỆC
-- THÊM LỊCH LÀM VIỆC
CREATE PROCEDURE SP_THEMLICHLAMVIEC
	@IDNHANVIEN CHAR(8),
	@NGAY DATE,
	@THANG INT,
	@NAM INT,
	@IDCALAM INT
AS
BEGIN TRAN

	-- Kiểm tra ràng buộc ngày làm việc
	IF CONVERT(DATE, CONCAT(@NAM, '-', @THANG, '-', @NGAY)) < GETDATE()
	BEGIN
		RAISERROR(N'Không thể thêm lịch làm việc từ ngày hiện tại trở về trước.', 16, 1)
		ROLLBACK TRAN
		RETURN
	END

	-- Kiểm tra ràng buộc trùng lặp
	IF EXISTS (SELECT 1 FROM LICHLAMVIEC WHERE IDNHANVIEN = @IDNHANVIEN AND NGAY = @NGAY AND THANG = @THANG AND NAM = @NAM)
	BEGIN
		RAISERROR(N'Không thể thêm lịch làm việc. Nhân viên đã có lịch làm việc trong ngày này.', 16, 1)
		ROLLBACK TRAN
		RETURN
	END

	-- Thực hiện thêm lịch làm việc vào bảng
	INSERT INTO LICHLAMVIEC (IDNHANVIEN, NGAY, THANG, NAM, IDCALAM)
	VALUES (@IDNHANVIEN, @NGAY, @THANG, @NAM, @IDCALAM)

COMMIT TRAN
GO

-- CHỈNH SỬA LỊCH LÀM VIỆC
CREATE PROCEDURE SP_KIEMTRALICHLAMVIEC
AS
	@IDNHANVIEN CHAR(8),
	@NGAY DATE,
	@THANG INT,
	@NAM INT,
	@IDCALAM INT
BEGIN TRAN

	-- Kiểm tra ràng buộc không được xóa/chỉnh sửa ca làm việc của ngày hiện tại và quá khứ
	IF EXISTS (SELECT * FROM LICHLAMVIEC WHERE CONVERT(DATE, CONCAT(NAM, '-', THANG, '-', NGAY)) <= GETDATE())
	BEGIN
		RAISERROR(N'Không được xóa/chỉnh sửa ca làm việc của ngày hiện tại và quá khứ.', 16, 1)
		ROLLBACK TRAN
		RETURN
	END

	--Tiến hành chỉnh sửa
	IF NOT EXISTS (SELECT * FROM LICHLAMVIEC WHERE IDNHANVIEN = @IDNHANVIEN AND NGAY = @NGAY AND THANG = @THANG AND NAM = @NAM AND @IDCALAM = IDCALAM)
	BEGIN
		UPDATE LICHLAMVIEC SET IDCALAM = @IDCALAM WHERE IDNHANVIEN = @IDNHANVIEN AND NGAY = @NGAY AND THANG = @THANG AND NAM = @NAM AND @IDCALAM = IDCALAM
	END
COMMIT TRAN
GO

-- XÓA LỊCH LÀM VIỆC
CREATE PROCEDURE SP_XOALICHLAMVIEC
	@IDNHANVIEN CHAR(8),
	@NGAY DATE,
	@THANG INT,
	@NAM INT
AS
BEGIN TRAN

	-- Kiểm tra ràng buộc không được xóa/chỉnh sửa ca làm việc của ngày hiện tại và quá khứ
	IF EXISTS (SELECT * FROM LICHLAMVIEC WHERE CONVERT(DATE, CONCAT(NAM, '-', THANG, '-', NGAY)) <= GETDATE())
	BEGIN
		RAISERROR(N'Không được xóa/chỉnh sửa ca làm việc của ngày hiện tại và quá khứ.', 16, 1)
		ROLLBACK TRAN
		RETURN
	END

	-- Tiến hành xóa
	DELETE FROM LICHLAMVIEC WHERE IDNHANVIEN = @IDNHANVIEN AND NGAY = @NGAY AND THANG = @THANG AND NAM = @NAM AND @IDCALAM = IDCALAM

COMMIT TRAN
GO

