USE QLPK_CSDL
GO

-- ĐĂNG KÝ NHÂN VIÊN
CREATE OR ALTER PROCEDURE dangky
    @SDT CHAR(8),
    @MATKHAU VARCHAR(10)
AS
BEGIN
    BEGIN TRY
        BEGIN TRAN;
        -- Kiểm tra xem tên người dùng đã tồn tại chưa
        IF EXISTS (SELECT 1 FROM NHANVIEN WHERE SODIENTHOAINV = @SDT)
        BEGIN
            PRINT 'Tên người dùng đã tồn tại';
            ROLLBACK;
            RETURN;
        END

        -- Thêm mới người dùng
        INSERT INTO NHANVIEN(SODIENTHOAINV, MATKHAU)
        VALUES (@SDT, @MATKHAU);
        COMMIT;
    END TRY
    BEGIN CATCH
        PRINT 'Lỗi hệ thống';
        ROLLBACK;
    END CATCH
END;

--ĐĂNG NHẬP
GO
CREATE OR ALTER PROCEDURE dangnhap
    @SDT CHAR(10),
    @MATKHAU VARCHAR(10)
AS
BEGIN
    BEGIN TRY
        BEGIN TRAN;
        -- Kiểm tra xem người dùng có tồn tại và thông tin đúng không
        IF EXISTS (SELECT 1 FROM NHANVIEN WHERE SODIENTHOAINV = @SDT AND MATKHAU = @MATKHAU)
        BEGIN
			SELECT IDNHANVIEN, IDPHONGKHAM, LOAINV
			FROM NHANVIEN NV
			WHERE NV.SODIENTHOAINV = @SDT AND MATKHAU = @MATKHAU
            PRINT N'Đăng nhập thành công';
        END
		ELSE IF EXISTS (SELECT 1 FROM HOSOBENHNHAN WHERE SODIENTHOAIBN = @SDT AND MATKHAU = @MATKHAU)
		BEGIN
			DECLARE @BN CHAR(2)
			SET @BN = 'BN'
			SELECT IDBENHNHAN AS IDNHANVIEN, IDPHONGKHAM, @BN AS LOAINV
			FROM HOSOBENHNHAN 
			WHERE SODIENTHOAIBN = @SDT AND MATKHAU = @MATKHAU
			PRINT N'ĐĂNG NHẬP THÀNH CÔNG'
		END
		ELSE
        BEGIN
            PRINT N'Đăng nhập thất bại';
			ROLLBACK;
			RETURN;
        END
        COMMIT;
    END TRY
    BEGIN CATCH
        PRINT 'Lỗi hệ thống';
        ROLLBACK;
    END CATCH
END;

EXEC dangnhap '0123456789', 'ABC12345'

--XEM DANH SÁCH NHÂN VIÊN
GO
CREATE OR ALTER PROC xemdanhsachnhanvien 
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN 
			SELECT * FROM NHANVIEN
		COMMIT TRAN
	END TRY
	BEGIN CATCH
			PRINT N'LỖI HỆ THỐNG'
			ROLLBACK TRAN
	END CATCH
END
                 

-- TÌM KIẾM THÔNG TIN QUA ID || XEM THÔNG TIN CHI TIẾT NHÂN VIÊN
GO
CREATE OR ALTER PROC timkiemnhanvienbangid
	@IDNHANVIEN CHAR(8)
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			IF EXISTS (SELECT 1 FROM NHANVIEN WHERE @IDNHANVIEN = IDNHANVIEN)
			BEGIN
				SELECT * FROM NHANVIEN WHERE IDNHANVIEN = @IDNHANVIEN
			END
			ELSE
			BEGIN
				PRINT N'KHÔNG TÌM THẤY NHÂN VIÊN';
				ROLLBACK;
				RETURN;
			END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG';
		ROLLBACK;
	END CATCH
END

EXEC timkiemnhanvienbangid 'NS000003'

--TÌM KIẾM THÔNG TIN QUA TÊN
GO
CREATE OR ALTER PROC timkiemnhanvienbangten @TEN NVARCHAR(50)
AS 
BEGIN
	BEGIN TRY
		BEGIN TRAN
			IF (@TEN IS NULL)
			BEGIN
				PRINT N'KHÔNG CÓ THÔNG TIN TÌM KIẾM'
				ROLLBACK TRAN;
				RETURN;
			END
			IF EXISTS (SELECT 1 FROM NHANVIEN NV WHERE NV.TENNV LIKE '%' + @TEN + '%')
			BEGIN
				SELECT *
				FROM NHANVIEN NV
				WHERE NV.TENNV LIKE '%' + @TEN + '%'
			END
			ELSE 
			BEGIN
				PRINT N'KHÔNG TÌM THẤY NHÂN VIÊN'
				ROLLBACK;
				RETURN;
			END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN;
	END CATCH
END 

EXEC timkiemnhanvienbangten 'Mitchell'
SELECT * FROM NHANVIEN WHERE IDNHANVIEN = 'NS000003'

--XÓA NHÂN VIÊN
GO
CREATE OR ALTER PROC xoanhanvien 
		@IDNHANVIEN CHAR(8)
AS 
BEGIN
	BEGIN TRY
		BEGIN TRAN
			IF NOT EXISTS (SELECT 1 IDNHANVIEN FROM NHANVIEN WHERE IDNHANVIEN = @IDNHANVIEN)
			BEGIN
				PRINT N'KHÔNG TỒN TẠI NHÂN VIÊN';
				ROLLBACK;
				RETURN;
			END
			ELSE 
			BEGIN
				DELETE FROM NHANVIEN
				WHERE IDNHANVIEN = @IDNHANVIEN
			END
		COMMIT
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG';
		ROLLBACK;
	END CATCH
END
EXEC xoanhanvien 'NV000300'

--THÊM NHÂN VIÊN
GO
CREATE OR ALTER PROC themnhanvien
		@IDNHANVIEN CHAR(8),
		@TENNV NVARCHAR(50),
		@NAMSINH DATE,
		@GIOITINH NVARCHAR(3),
		@SDT CHAR(10),
		@MATKHAU VARCHAR(10),
		@LOAINV CHAR(2),
		@IDPHONGKHAM CHAR(3)
AS 
BEGIN
	BEGIN TRY
		BEGIN TRAN
			IF @IDNHANVIEN IS NULL
			BEGIN
				PRINT N'ID NHÂN VIÊN KHÔNG ĐƯỢC TRỐNG';
				ROLLBACK;
				RETURN;
			END
			IF @TENNV IS NULL
			BEGIN 
				PRINT N'TÊN NHÂN VIÊN KHÔNG ĐƯỢC TRỐNG';
				ROLLBACK;
				RETURN;
			END
			IF @NAMSINH IS NULL
			BEGIN
				PRINT N'NĂM SINH KHÔNG ĐƯỢC TRỐNG';
				ROLLBACK;
				RETURN;
			END
			IF @GIOITINH IS NULL
			BEGIN 
				PRINT N'GIỚI TÍNH KHÔNG ĐƯỢC TRỐNG';
				ROLLBACK;
				RETURN;
			END
			IF @SDT IS NULL
			BEGIN
				PRINT N'SỐ ĐIỆN THOẠI KHÔNG ĐƯỢC TRỐNG';
				ROLLBACK;
				RETURN;
			END
			IF @MATKHAU IS NULL
			BEGIN
				PRINT N'MẬT KHẨU KHÔNG ĐƯỢC TRỐNG';
				ROLLBACK;
				RETURN;
			END
			IF @LOAINV IS NULL
			BEGIN
				PRINT N'LOẠI NHÂN VIÊN KHÔNG ĐƯỢC TRỐNG';
				ROLLBACK;
				RETURN;
			END
			IF @IDPHONGKHAM IS NULL
			BEGIN
				PRINT N'ID PHÒNG KHÁM KHÔNG ĐƯỢC TRỐNG';
				ROLLBACK;
				RETURN;
			END
			IF EXISTS (SELECT 1 FROM NHANVIEN NV WHERE NV.IDNHANVIEN = @IDNHANVIEN OR NV.SODIENTHOAINV = @SDT)
			BEGIN
				PRINT N'BỆNH NHÂN ĐÃ TỒN TẠI';
				ROLLBACK;
				RETURN;
			END
			ELSE 
			BEGIN
				INSERT QLPK_CSDL.dbo.NHANVIEN(IDNHANVIEN, TENNV, NAMSINHNV, GIOITINHNV, SODIENTHOAINV, MATKHAU, LOAINV, IDPHONGKHAM)
				VALUES (@IDNHANVIEN, @TENNV, @NAMSINH, @GIOITINH, @SDT, @MATKHAU, @LOAINV, @IDPHONGKHAM)
			END
		COMMIT 
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG';
		ROLLBACK;
	END CATCH
END

EXEC themnhanvien 'NV000300', 'NGO QUOC QUY', '2003-08-23', 'NAM', '0828770239', 'ABC123456', 'NV', 'P01'
--DELETE FROM NHANVIEN WHERE IDNHANVIEN = 'NV000300'
--SELECT * FROM NHANVIEN WHERE IDNHANVIEN = 'NV000300'
--select * from HOSOBENHNHAN
--select * from LICHLAMVIEC where IDNHANVIEN = 'NS000003' AND IDCALAM = 'C3' AND NAM ='2025'
--EXEC SP_THEM_LICH_LAM_VIEC 'NS000003', '2025-01-09', 'C2'
--delete from LICHHEN
--select * from lichhen where BENHNHAN = 'BN100001'