USE QLPK_CSDL
GO
--Tạo file group 
ALTER DATABASE QLPK_CSDL
ADD FILEGROUP FG_LH_1

ALTER DATABASE QLPK_CSDL
ADD FILEGROUP FG_LH_2

ALTER DATABASE QLPK_CSDL
ADD FILEGROUP FG_LLV_1

ALTER DATABASE QLPK_CSDL
ADD FILEGROUP FG_LLV_2

ALTER DATABASE QLPK_CSDL
ADD FILEGROUP FG_BDT_1

ALTER DATABASE QLPK_CSDL
ADD FILEGROUP FG_BDT_2

ALTER DATABASE QLPK_CSDL
ADD FILEGROUP FG_HD_1

ALTER DATABASE QLPK_CSDL
ADD FILEGROUP FG_HD_2

ALTER DATABASE QLPK_CSDL
ADD FILEGROUP FG_DT_1

ALTER DATABASE QLPK_CSDL
ADD FILEGROUP FG_DT_2

-- Xem file groups
SELECT name as [File Group Name]
FROM sys.filegroups
WHERE type = 'FG'
GO

-- Tạo datafiles
--LICHHEN
ALTER DATABASE QLPK_CSDL
ADD FILE (NAME = FG_LH_2022,
FILENAME = 'D:\DB_Partition\DBPartition_LH_1.ndf',
SIZE = 1MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1
) TO FILEGROUP FG_LH_1

ALTER DATABASE QLPK_CSDL
ADD FILE (NAME = FG_LH_2023,
FILENAME = 'D:\DB_Partition\DBPartition_LH_2.ndf',
SIZE = 1MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1
) TO FILEGROUP FG_LH_2

--LICHLAMVIEC
ALTER DATABASE QLPK_CSDL
ADD FILE (NAME = FG_LLV_2022,
FILENAME = 'D:\DB_Partition\DBPartition_LLV_1.ndf',
SIZE = 1MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1
) TO FILEGROUP FG_LLV_1

ALTER DATABASE QLPK_CSDL
ADD FILE (NAME = FG_LLV_2023,
FILENAME = 'D:\DB_Partition\DBPartition_LLV_2.ndf',
SIZE = 1MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1
) TO FILEGROUP FG_LLV_2

--BUOIDIEUTRI
ALTER DATABASE QLPK_CSDL
ADD FILE (NAME = FG_BDT_2022,
FILENAME = 'D:\DB_Partition\DBPartition_BDT_1.ndf',
SIZE = 1MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1
) TO FILEGROUP FG_BDT_1

ALTER DATABASE QLPK_CSDL
ADD FILE (NAME = FG_BDT_2023,
FILENAME = 'D:\DB_Partition\DBPartition_BDT_2.ndf',
SIZE = 1MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1
) TO FILEGROUP FG_BDT_2

--HOADON
ALTER DATABASE QLPK_CSDL
ADD FILE (NAME = FG_HD_2022,
FILENAME = 'D:\DB_Partition\DBPartition_HD_1.ndf',
SIZE = 1MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1
) TO FILEGROUP FG_HD_1

ALTER DATABASE QLPK_CSDL
ADD FILE (NAME = FG_HD_2023,
FILENAME = 'D:\DB_Partition\DBPartition_HD_2.ndf',
SIZE = 1MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1
) TO FILEGROUP FG_HD_2

--DONTHUOC
ALTER DATABASE QLPK_CSDL
ADD FILE (NAME = FG_DT_2022,
FILENAME = 'D:\DB_Partition\DBPartition_DT_1.ndf',
SIZE = 1MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1
) TO FILEGROUP FG_DT_1

ALTER DATABASE QLPK_CSDL
ADD FILE (NAME = FG_DT_2023,
FILENAME = 'D:\DB_Partition\DBPartition_DT_2.ndf',
SIZE = 1MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1
) TO FILEGROUP FG_DT_2

--Xem datafiles
SELECT name as [DB FileName],physical_name as
[DB File Path]
FROM sys.database_files
where type_desc = 'ROWS'
GO

--Partition function and schema
--LICHHEN
CREATE PARTITION FUNCTION LH_YearPartitions(DATE)
AS RANGE RIGHT
FOR VALUES('2023-01-01')

CREATE PARTITION SCHEME LH_YearPartitionsScheme
AS PARTITION LH_YearPartitions
TO (FG_LH_1, FG_LH_2)

--LICHLAMVIEC
CREATE PARTITION FUNCTION LLV_YearPartitions(INT)
AS RANGE RIGHT
FOR VALUES('2023')

CREATE PARTITION SCHEME LLV_YearPartitionsScheme
AS PARTITION LLV_YearPartitions
TO (FG_LLV_1, FG_LLV_2)

--BUOIDIEUTRI
CREATE PARTITION FUNCTION BDT_YearPartitions(DATE)
AS RANGE RIGHT
FOR VALUES('2023-01-01')

CREATE PARTITION SCHEME BDT_YearPartitionsScheme
AS PARTITION BDT_YearPartitions
TO (FG_BDT_1, FG_BDT_2)

--HOADON
CREATE PARTITION FUNCTION HD_YearPartitions(DATE)
AS RANGE RIGHT
FOR VALUES('2023-01-01')

CREATE PARTITION SCHEME HD_YearPartitionsScheme
AS PARTITION HD_YearPartitions
TO (FG_HD_1, FG_HD_2)

--DONTHUOC
CREATE PARTITION FUNCTION DT_YearPartitions(DATE)
AS RANGE RIGHT
FOR VALUES('2023-01-01')

CREATE PARTITION SCHEME DT_YearPartitionsScheme
AS PARTITION DT_YearPartitions
TO (FG_DT_1, FG_DT_2)

--ĐỔI CLUSTERED INDEX CỦA PK THÀNH NON-CLUSTERED VÀ TẠO CLUSTERED INDEX CHO CỘT CHIA TRONG PARTITION
--LICHHEN
ALTER TABLE LICHHEN
DROP CONSTRAINT PK_LICHHEN

ALTER TABLE LICHHEN
ADD PRIMARY KEY
NONCLUSTERED(BACSI, BENHNHAN, NGAYHEN, THOIGIANHEN)
ON [PRIMARY]

CREATE CLUSTERED INDEX IX_LICHHEN_YEAR
ON LICHHEN ( NGAYHEN) 
ON LH_YearPartitionsScheme(NGAYHEN)

--LICHLAMVIEC
ALTER TABLE LICHLAMVIEC
DROP CONSTRAINT PK_LICHLAMVIEC

ALTER TABLE LICHLAMVIEC
ADD PRIMARY KEY
NONCLUSTERED(IDNHANVIEN, NGAY, THANG, NAM, IDCALAM)
ON [PRIMARY]

CREATE CLUSTERED INDEX IX_LICHLAMVIEC_YEAR
ON LICHLAMVIEC ( NAM) 
ON LLV_YearPartitionsScheme(NAM)

--BUOIDIEUTRI
ALTER TABLE CHITIETDIEUTRI
DROP CONSTRAINT FK_CTDIEUTRI_BDT

ALTER TABLE DONTHUOC
DROP CONSTRAINT FK_DT_BDT

ALTER TABLE HOADON
DROP CONSTRAINT FK_HD_BDT

ALTER TABLE BUOIDIEUTRI
DROP CONSTRAINT PK_BUOIDT

ALTER TABLE BUOIDIEUTRI
ADD PRIMARY KEY
NONCLUSTERED(IDBUOIDIEUTRI)
ON [PRIMARY]

CREATE CLUSTERED INDEX IX_BUOIDIEUTRI_YEAR
ON BUOIDIEUTRI ( NGAYDT) 
ON BDT_YearPartitionsScheme(NGAYDT)

ALTER TABLE CHITIETDIEUTRI
ADD CONSTRAINT FK_CTDIEUTRI_BDT
	FOREIGN KEY (IDBUOIDIEUTRI)
	REFERENCES BUOIDIEUTRI(IDBUOIDIEUTRI)

ALTER TABLE DONTHUOC
ADD CONSTRAINT FK_DT_BDT
	FOREIGN KEY (IDBUOIDIEUTRI)
	REFERENCES BUOIDIEUTRI(IDBUOIDIEUTRI)

ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_BDT
	FOREIGN KEY (IDBUOIDIEUTRI)
	REFERENCES BUOIDIEUTRI(IDBUOIDIEUTRI)

--HOADON
ALTER TABLE HOADON
DROP CONSTRAINT PK_HOADON

ALTER TABLE HOADON
ADD PRIMARY KEY
NONCLUSTERED(IDHOADON)
ON [PRIMARY]

CREATE CLUSTERED INDEX IX_HOADON_YEAR
ON HOADON ( NGAYGIAODICH) 
ON HD_YearPartitionsScheme(NGAYGIAODICH)

--DONTHUOC
ALTER TABLE DONTHUOC
DROP CONSTRAINT PK_DONTHUOC

ALTER TABLE DONTHUOC
ADD PRIMARY KEY
NONCLUSTERED(IDDONTHUOC)
ON [PRIMARY]

CREATE CLUSTERED INDEX IX_DONTHUOC_YEAR
ON DONTHUOC ( NGAYCAP) 
ON DT_YearPartitionsScheme(NGAYCAP)
